 
version: "3"

services:
  server:
    build: server/
    env_file:
      environment.env 

    ports:
      - "5000:5000"

  client:
    build: client/
    env_file:
      environment.env 
  
    depends_on:
      - server

    restart: on-failure